feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    br.com.ariki.music.suggestion.by.weather: DEBUG


#Custom
openweathermap:
  feign:
    name: open-weather-map-api
    url: https://api.openweathermap.org/data/2.5
spotify:
  feign:
    account:
      name: spotify-account-api
      url: https://accounts.spotify.com
    api:
      name: spotify-api
      url: https://api.spotify.com/v1
    playlist:
      party-id: 37i9dQZF1DXaXB8fQg7xif
      pop-id: 37i9dQZF1DWUa8ZRTfalHk
      rock-id: 37i9dQZF1DX8FwnYE6PRvL
      classical-id: 37i9dQZF1DWWEJlAGA9gs0
